export const glossary = [
  {
    term: "AD",
    kind: "abbreviation",
    also: ["Anno Domini"],
    body: "Latin for “in the year of the Lord.” Dates after the traditional birth of Jesus. This site uses AD for first-century years (for example 33 AD).",
  },
  {
    term: "Abscess",
    kind: "term",
    body: "A pocket of pus under the skin or in tissue. Ancient surgeons lanced (cut open) abscesses to drain them — one of the few operations that still looks wise.",
  },
  {
    term: "Alexandria",
    kind: "term",
    body: "Egyptian city and the great medical school of the Hellenistic world. Much of the surgery Celsus describes was learned from Alexandrian tradition.",
  },
  {
    term: "Allicin",
    kind: "term",
    body: "A sulfur compound formed when garlic is crushed. It has mild antimicrobial effects — one reason household garlic was not only folklore.",
  },
  {
    term: "Amputation",
    kind: "term",
    body: "Cutting off a limb, usually for gangrene or a smashed, dying extremity. Done with cautery to stop bleeding. Many patients died of shock or infection afterward.",
  },
  {
    term: "Anesthetic",
    kind: "term",
    also: ["Anaesthetic"],
    body: "A drug that takes away pain or consciousness. First-century surgeons had no reliable general anesthetic. Wine was usual; mandrake or opium were possible but uncertain in Judea.",
  },
  {
    term: "Anointing",
    kind: "term",
    body: "Rubbing oil on the body for honor, ritual, or healing. James 5:14 tells the church to pray and anoint the sick with oil.",
  },
  {
    term: "Antimicrobial",
    kind: "term",
    body: "Able to slow or kill microbes (bacteria, fungi). Ancients did not know germs, but honey, wine, myrrh, and garlic can act this way in part.",
  },
  {
    term: "Antiseptic",
    kind: "term",
    body: "A substance used on skin or wounds to reduce infection. Wine and honey were the best everyday antiseptics of the period.",
  },
  {
    term: "Arteriotomy",
    kind: "term",
    body: "Opening an artery, not just a vein, to let blood. A more dangerous cousin of venesection, described for some eye complaints.",
  },
  {
    term: "Asclepiades of Bithynia",
    kind: "term",
    body: "Greek physician in Rome (c. 130–40 BC) who preferred diet, baths, and wine over heavy bleeding and purging. He taught that the body is pores and particles, not four fluids.",
  },
  {
    term: "Astringent",
    kind: "term",
    body: "A substance that tightens or dries tissue — for example pomegranate rind used on loose bowels or weeping sores.",
  },
  {
    term: "Atomist",
    kind: "term",
    also: ["Corpuscular"],
    body: "A medical theory that the body is made of particles and pores, not four humors. Asclepiades is the famous first-century-BC voice of this view in Rome.",
  },
  {
    term: "Atropine",
    kind: "term",
    body: "A powerful alkaloid in nightshade plants such as mandrake. It can sedate — and can kill. Named here only to explain why mandrake was both medicine and poison.",
  },
  {
    term: "BC",
    kind: "abbreviation",
    also: ["Before Christ"],
    body: "Years before the traditional birth of Jesus (for example 4 BC). Same idea as BCE (“Before the Common Era”).",
  },
  {
    term: "BCE",
    kind: "abbreviation",
    also: ["Before the Common Era"],
    body: "Secular date label meaning the same span as BC. This site mostly writes BC.",
  },
  {
    term: "Balm of Gilead",
    kind: "term",
    also: ["Balsam", "Commiphora gileadensis"],
    body: "Aromatic resin from balsam shrubs grown especially near Jericho and Ein Gedi. Judea’s most famous luxury drug, praised by Pliny and Dioscorides.",
  },
  {
    term: "Ben Sira",
    kind: "term",
    also: ["Sirach", "Ecclesiasticus"],
    body: "Jewish wisdom book (early 2nd century BC) still read in Jesus’s world. Chapter 38 tells readers to honor physicians and not despise earth-grown medicines.",
  },
  {
    term: "Bitumen",
    kind: "term",
    body: "Natural tar from the Dead Sea, traded as a mineral drug and sealant. A Judean export alongside balsam.",
  },
  {
    term: "Black bile",
    kind: "term",
    also: ["Melaina chole"],
    body: "The cold, dry humor of autumn and earth. Excess was thought to cause melancholy — sadness, heaviness, and dark thoughts. More inferred than seen.",
  },
  {
    term: "Bloodletting",
    kind: "term",
    body: "Removing blood to “rebalance” the body. Done by opening a vein, applying leeches, or cupping. The most common learned procedure of the age, and usually harmful.",
  },
  {
    term: "c.",
    kind: "abbreviation",
    also: ["ca.", "circa"],
    body: "Latin circa, “approximately.” Used with uncertain dates (c. 4 BC means “about 4 BC”).",
  },
  {
    term: "CE",
    kind: "abbreviation",
    also: ["Common Era"],
    body: "Secular date label meaning the same years as AD. This site mostly writes AD.",
  },
  {
    term: "Caldarium",
    kind: "term",
    body: "The hot room of a Roman bath. Used with the tepidarium (warm) and frigidarium (cold).",
  },
  {
    term: "Calor, rubor, tumor, dolor",
    kind: "term",
    also: ["Four signs of inflammation"],
    body: "Latin for heat, redness, swelling, and pain. Celsus’s four signs of inflammation — still taught in medical schools.",
  },
  {
    term: "Carminative",
    kind: "term",
    body: "A herb or spice that eases gas and bloating — cumin, fennel, dill, mint.",
  },
  {
    term: "Cathartic",
    kind: "term",
    body: "A strong laxative that empties the bowel. Senna is the classic example. Humoral doctors used cathartics to “purge” extra fluids.",
  },
  {
    term: "Cautery",
    kind: "term",
    also: ["Cauterization"],
    body: "A heated iron used to stop bleeding or burn away dead or infected tissue. Extremely painful; wine was given for courage.",
  },
  {
    term: "Celsus",
    kind: "term",
    also: ["Aulus Cornelius Celsus", "De Medicina"],
    body: "Roman writer of De Medicina (about the 30s AD), the best encyclopaedia of elite medicine from Jesus’s own generation. Diet, drugs, and surgery.",
  },
  {
    term: "Choleric",
    kind: "term",
    body: "Temperament of yellow bile: hot, dry, passionate, quick to anger. Summer and fire in the humoral chart.",
  },
  {
    term: "Commiphora",
    kind: "term",
    body: "The plant genus of myrrh and of balsam (balm of Gilead). Trees and shrubs that yield aromatic resin.",
  },
  {
    term: "Corpus",
    kind: "term",
    also: ["Hippocratic Corpus"],
    body: "A collection of writings under one name. The Hippocratic Corpus is the body of Greek medical texts attached to Hippocrates.",
  },
  {
    term: "Counter-irritation",
    kind: "term",
    body: "Irritating the skin on purpose (as with a mustard plaster) in the hope of helping a deeper ache by drawing blood to the surface.",
  },
  {
    term: "Cupping",
    kind: "term",
    body: "Heated cups placed on the skin to suck blood or “vapors” toward the surface. Wet cupping also cuts the skin so blood enters the cup.",
  },
  {
    term: "De Materia Medica",
    kind: "term",
    body: "Greek herbal by Dioscorides (c. 50–70 AD): about 600 plants and 1,000 preparations. The standard pharmacopoeia of Europe and the Near East for some 1,500 years.",
  },
  {
    term: "De Medicina",
    kind: "term",
    body: "Celsus’s Latin medical encyclopaedia, written about the 30s AD. Eight books covering diet, pharmacy, and surgery.",
  },
  {
    term: "Decoction",
    kind: "term",
    body: "A tea made by boiling plant parts (often roots or bark) rather than steeping leaves. Licorice root was commonly decocted.",
  },
  {
    term: "Demulcent",
    kind: "term",
    body: "A soothing, coating preparation for raw throats or guts — honey and licorice are examples.",
  },
  {
    term: "Dioscorides",
    kind: "term",
    also: ["Pedanius Dioscorides"],
    body: "Greek army physician (c. 40–90 AD) who wrote De Materia Medica after travelling the eastern Mediterranean, including Petra.",
  },
  {
    term: "Diuretic",
    kind: "term",
    body: "Something that increases urine. Parsley and lovage were used this way in kitchen-pharmacy.",
  },
  {
    term: "Dudaim",
    kind: "term",
    body: "Hebrew word in Genesis for mandrake fruits, treated there as a fertility charm.",
  },
  {
    term: "Ein Gedi",
    kind: "term",
    body: "Oasis on the Dead Sea famous for balsam groves, alongside the gardens near Jericho.",
  },
  {
    term: "Electuary",
    kind: "term",
    body: "A paste of powdered herbs mixed with honey so bitter drugs could be swallowed.",
  },
  {
    term: "Emetic",
    kind: "term",
    body: "A drug that causes vomiting. Used to empty the stomach and, in theory, extra humors.",
  },
  {
    term: "Encyclopaedia",
    kind: "term",
    also: ["Encyclopedia"],
    body: "A work that tries to cover a whole field. Celsus’s De Medicina is the surviving medical part of a larger Roman encyclopaedia.",
  },
  {
    term: "Essenes",
    kind: "term",
    body: "A Jewish sect of the Second Temple period, associated by some with Qumran. Josephus says they were interested in roots and healing lore.",
  },
  {
    term: "Ezov",
    kind: "term",
    also: ["Hyssop"],
    body: "Biblical plant name, widely identified with Syrian oregano (Origanum syriacum), not European garden hyssop. Used in ritual sprinkling and folk teas.",
  },
  {
    term: "Flux",
    kind: "term",
    body: "An old word for a flow from the body — diarrhea, discharge, or watering eyes. Humoral doctors tried to stop, redirect, or encourage fluxes.",
  },
  {
    term: "Frigidarium",
    kind: "term",
    body: "The cold-water room or plunge of a Roman bath.",
  },
  {
    term: "Galen",
    kind: "term",
    also: ["Galen of Pergamon"],
    body: "Physician of the 2nd century AD (after Jesus). Later ages read all ancient medicine through Galen. This site flags him so he is not back-dated into the 30s AD.",
  },
  {
    term: "Galenic",
    kind: "term",
    body: "Medicine as later systematized by Galen: a tight humoral system. In 30 AD that system did not yet exist in finished form.",
  },
  {
    term: "Gangrene",
    kind: "term",
    body: "Death of tissue, often in a limb, with rotting and spreading infection. Amputation was the last resort.",
  },
  {
    term: "Gospels",
    kind: "term",
    body: "The four New Testament narratives of Jesus’s life (Matthew, Mark, Luke, John). They record healings, oil and wine on wounds, and Luke as a physician.",
  },
  {
    term: "Haima",
    kind: "term",
    body: "Greek for blood, the hot-wet humor of spring and air. Linked to the sanguine temperament.",
  },
  {
    term: "Herniotomy",
    kind: "term",
    body: "Surgery to repair a hernia (a bulge of tissue through a weak spot). Celsus describes specialist operations of this kind — not village craft.",
  },
  {
    term: "Hippocrates",
    kind: "term",
    also: ["Hippocrates of Kos"],
    body: "Greek physician (c. 460–370 BC). Later doctors claimed him as ancestor. Observation, prognosis, and regimen before the knife are the Hippocratic inheritance.",
  },
  {
    term: "Hippocratic",
    kind: "term",
    body: "In the tradition of Hippocrates: natural causes of disease, watching the course of fever, diet and rest before heroic cutting.",
  },
  {
    term: "Humor",
    kind: "term",
    also: ["Humoral theory", "Four humors"],
    body: "One of four bodily fluids — blood, phlegm, yellow bile, black bile — whose balance was thought to make health. The main scientific model of the Greco-Roman clinic.",
  },
  {
    term: "Infusion",
    kind: "term",
    body: "A tea made by steeping leaves or flowers in hot water (gentler than a decoction).",
  },
  {
    term: "Josephus",
    kind: "term",
    body: "Jewish historian of the 1st century AD. He describes balsam plantations, Essenes, and the war that ended in 70 AD.",
  },
  {
    term: "Judea",
    kind: "term",
    also: ["Judaea"],
    body: "The Roman-period name for the southern Jewish homeland around Jerusalem. A client landscape of Torah, Greek cities, and balsam estates.",
  },
  {
    term: "Julio-Claudian",
    kind: "term",
    body: "The first Roman imperial dynasty (Augustus through Nero). Jesus’s lifetime falls in this era (especially Tiberius).",
  },
  {
    term: "Lancet",
    kind: "term",
    body: "A small, sharp blade for opening a vein or an abscess.",
  },
  {
    term: "Latex",
    kind: "term",
    body: "Milky sap of some plants. Fig latex is caustic and was used on warts and boils; it is not the same as rubber-tree latex.",
  },
  {
    term: "Leech",
    kind: "term",
    body: "A blood-sucking worm applied to the skin as a gentler form of bloodletting. The animal measures the blood for you.",
  },
  {
    term: "Lemnian earth",
    kind: "term",
    also: ["Terra Lemnia", "Terra sigillata"],
    body: "A stamped medicinal clay from the island of Lemnos, sold as a brand-name mineral drug for wounds and swallowed as an antidote.",
  },
  {
    term: "Lentisk",
    kind: "term",
    also: ["Mastic", "Pistacia lentiscus"],
    body: "A Mediterranean shrub whose resin (especially from Chios) was chewed for the stomach and breath.",
  },
  {
    term: "Levitical",
    kind: "term",
    also: ["Leviticus"],
    body: "Belonging to the book of Leviticus, the Torah’s priestly law. Chapters 13–15 cover skin disease, fluxes, and washing — holiness with a quarantine diagram.",
  },
  {
    term: "Ligature",
    kind: "term",
    body: "Tying a blood vessel with thread to stop bleeding. Celsus records it clearly; many later centuries forgot the technique.",
  },
  {
    term: "Lithotomy",
    kind: "term",
    body: "Cutting for bladder stone. A specialist operation in Celsus, not something a village healer attempted.",
  },
  {
    term: "Luke",
    kind: "term",
    body: "Companion of Paul, called “the beloved physician” in Colossians 4:14. Traditional author of the Gospel of Luke and Acts.",
  },
  {
    term: "Lye",
    kind: "term",
    also: ["Atriplex halimus"],
    body: "An alkaline washing substance. Judean saltbush could yield soap-ash; part of the land’s reputation for cleansing products.",
  },
  {
    term: "Mandrake",
    kind: "term",
    also: ["Mandragora"],
    body: "A Mediterranean nightshade with a forked root and narcotic alkaloids. Folklore treated it as a fertility charm; it is toxic in overdose.",
  },
  {
    term: "Materia medica",
    kind: "term",
    body: "Latin for “medical materials”: the plants, animal parts, and minerals used as drugs. Also the name of books that list them.",
  },
  {
    term: "Melancholic",
    kind: "term",
    also: ["Melancholy"],
    body: "Temperament of black bile: thoughtful, anxious, sleepless. Excess melancholy was treated with warmth, company, wine in measure — and sometimes, unwisely, bleeding.",
  },
  {
    term: "Methodist",
    kind: "term",
    body: "A Greek medical school that treated disease as the body being too tight (strictum) or too loose (laxum), rather than as four humors. One of several first-century options.",
  },
  {
    term: "Mikveh",
    kind: "term",
    also: ["Mikva’ot"],
    body: "A Jewish ritual bath of “living” (flowing or spring-fed) water. For purity before God, not a Roman spa — but it made washing ordinary.",
  },
  {
    term: "Mosaic Law",
    kind: "term",
    also: ["Torah", "Pentateuch"],
    body: "The Law of Moses: the first five books of the Hebrew Bible. Includes food rules, washing, and priestly inspection of skin disease.",
  },
  {
    term: "Myrrh",
    kind: "term",
    body: "Bitter resin of Commiphora trees from Arabia and East Africa. Used as incense, wound salve, perfume, and burial spice (John 19:39).",
  },
  {
    term: "Nard",
    kind: "term",
    also: ["Spikenard", "Nardostachys"],
    body: "Costly Himalayan aromatic oil. Mary of Bethany anoints Jesus with nard (John 12:3). Proof that Judea was wired into long-distance trade.",
  },
  {
    term: "Occlusive",
    kind: "term",
    body: "A dressing or oil that seals the skin and holds moisture in. Olive oil is occlusive: it soothes by covering, not by killing germs.",
  },
  {
    term: "Olibanum",
    kind: "term",
    also: ["Frankincense"],
    body: "The resin of Boswellia trees, burned as Temple incense and used on swellings and coughs.",
  },
  {
    term: "Opium",
    kind: "term",
    body: "Latex of the opium poppy, a true painkiller. Known in the wider Roman world; how often it reached a Galilean village is uncertain.",
  },
  {
    term: "Pharmacopoeia",
    kind: "term",
    body: "An official or standard list of drugs and how to prepare them. Dioscorides’ De Materia Medica functioned as the ancient world’s pharmacopoeia.",
  },
  {
    term: "Pharmacy",
    kind: "term",
    body: "The craft of preparing medicines (and the shop or chest that holds them). Distinct from surgery and from regimen.",
  },
  {
    term: "Phlebotomy",
    kind: "term",
    body: "Another word for venesection: cutting a vein to let blood.",
  },
  {
    term: "Phlegm",
    kind: "term",
    also: ["Phlegma"],
    body: "The cold, wet humor of winter and water. Mucus and sluggishness. Treated with heat, spices, steam, and mustard plasters.",
  },
  {
    term: "Phlegmatic",
    kind: "term",
    body: "Temperament of phlegm: calm, slow, steadfast, pale.",
  },
  {
    term: "Pliny the Elder",
    kind: "term",
    also: ["Natural History"],
    body: "Roman admiral and compiler (23–79 AD) of Natural History. He catalogues plants and folk cures, praises Judean balsam, and complains about Greek doctors.",
  },
  {
    term: "Poultice",
    kind: "term",
    also: ["Cataplasm"],
    body: "A wet mash of herbs, meal, or fruit spread on cloth and bound to the skin. King Hezekiah’s fig plaster (2 Kings 20:7) is the biblical type.",
  },
  {
    term: "Prognosis",
    kind: "term",
    body: "Telling the likely course of an illness. Hippocratic physicians were often valued more for prediction than for cure.",
  },
  {
    term: "Purging",
    kind: "term",
    also: ["Purge"],
    body: "Emptying the stomach (emetic) or bowel (cathartic) to remove “extra” humor. Senna is a typical purge.",
  },
  {
    term: "Qumran",
    kind: "term",
    body: "Settlement by the Dead Sea associated with the Dead Sea Scrolls and, in many reconstructions, with Essene life.",
  },
  {
    term: "Reduction",
    kind: "term",
    body: "Putting a broken bone back into line (pulling and aligning) before splinting. A good reduction can save a limb’s usefulness.",
  },
  {
    term: "Regimen",
    kind: "term",
    also: ["Dietetics"],
    body: "A prescribed pattern of food, wine, exercise, bathing, sleep, and sex. For learned doctors this was first-line treatment, before drugs or the knife.",
  },
  {
    term: "Resin",
    kind: "term",
    body: "Sticky plant gum that hardens in air — myrrh, balsam, frankincense, mastic. Often antimicrobial and used on wounds or as incense.",
  },
  {
    term: "Rofe",
    kind: "term",
    also: ["Rof'im"],
    body: "Hebrew for physician. Sirach treats the role as a gift from God, not as a pagan hobby.",
  },
  {
    term: "Salve",
    kind: "term",
    also: ["Ointment"],
    body: "A thick spread for the skin, usually oil plus wax and herbs. Stays put longer than a thin oil.",
  },
  {
    term: "Sanguine",
    kind: "term",
    body: "Temperament of blood: cheerful, generous, talkative, rosy. Excess was treated by cooling and, too often, by bleeding.",
  },
  {
    term: "Second Temple",
    kind: "term",
    body: "The period of Jewish history from the rebuilding of the Temple (late 6th century BC) until its destruction in 70 AD. Jesus’s lifetime is late Second Temple.",
  },
  {
    term: "Senna",
    kind: "term",
    also: ["Sennosides"],
    body: "Imported leaves that strongly stimulate the bowel. They work — and can cramp and dehydrate. A standard humoral purge.",
  },
  {
    term: "Sepsis",
    kind: "term",
    body: "Infection that has spread through the body, with fever and often death. Ancients saw the fever after a small wound as a bad sign; they had no name for bacteria.",
  },
  {
    term: "Sepphoris",
    kind: "term",
    body: "A rebuilt Greek-style city in Galilee near Nazareth. A likely market for Greek-trained physicians as well as village herbalists.",
  },
  {
    term: "Spp.",
    kind: "abbreviation",
    also: ["species plural"],
    body: "Latin species plural. After a genus name it means “several species of this plant,” for example Boswellia spp. (frankincense trees).",
  },
  {
    term: "Splint",
    kind: "term",
    body: "Sticks, reeds, or boards bound to a broken limb so the bone stays still while it heals.",
  },
  {
    term: "Strigil",
    kind: "term",
    body: "A curved metal scraper used in Roman baths to wipe off oil, sweat, and dirt after exercise.",
  },
  {
    term: "Strictum and laxum",
    kind: "term",
    body: "Methodist medical pair: the body too tight or too loose. Treatment aimed to relax or constrict, instead of balancing four humors.",
  },
  {
    term: "Tannins",
    kind: "term",
    body: "Plant compounds that bind and dry tissue. Pomegranate rind is rich in tannins, which is why it was used as an astringent.",
  },
  {
    term: "Temperament",
    kind: "term",
    body: "Character type tied to a dominant humor: sanguine, phlegmatic, choleric, melancholic. Thought to be physiology, not metaphor.",
  },
  {
    term: "Tepidarium",
    kind: "term",
    body: "The warm room of a Roman bath, between the hot caldarium and the cold frigidarium.",
  },
  {
    term: "Terra sigillata",
    kind: "term",
    body: "“Sealed earth”: stamped cakes of medicinal clay. Lemnian earth is the famous brand.",
  },
  {
    term: "Theriac",
    kind: "term",
    body: "A compound antidote paste, sometimes with dozens of ingredients. Already known in this world; later centuries made it famous.",
  },
  {
    term: "Thermae",
    kind: "term",
    body: "Public Roman baths. A civic machine of heat, oil, and cold water that physicians turned into prescriptions.",
  },
  {
    term: "Torah",
    kind: "term",
    body: "The Instruction: the first five books of the Hebrew Bible, and by extension Jewish law. Food, purity, and priestly medicine sit here.",
  },
  {
    term: "Tzara’at",
    kind: "term",
    body: "The skin affliction of Leviticus 13–14, often translated “leprosy” but covering several conditions. A priest diagnosed it; isolation followed.",
  },
  {
    term: "Venesection",
    kind: "term",
    also: ["Phlebotomy"],
    body: "Cutting a vein to let blood. The flagship procedure of humoral practice.",
  },
  {
    term: "Yellow bile",
    kind: "term",
    also: ["Xanthe chole"],
    body: "The hot, dry humor of summer and fire. Excess meant anger, burning stomach, jaundice, and acute inflammations. Choleric temperament.",
  },
];

export function glossaryLetter(term) {
  const ch = term.replace(/^["“]+/, "")[0];
  return ch ? ch.toUpperCase() : "#";
}
