export const humors = [
  {
    id: "blood",
    name: "Blood",
    greek: "Haima",
    temperament: "Sanguine",
    qualities: ["Hot", "Wet"],
    season: "Spring",
    element: "Air",
    color: "#9b2e2e",
    tone: "bg-[#9b2e2e]",
    character: "Cheerful, generous, talkative, rosy.",
    excess: "Fevers, flushing, nosebleeds, over-excitement.",
    treatments: "Bleeding, cooling foods, rest from wine and meat, spring purges.",
  },
  {
    id: "yellow-bile",
    name: "Yellow bile",
    greek: "Xanthe chole",
    temperament: "Choleric",
    qualities: ["Hot", "Dry"],
    season: "Summer",
    element: "Fire",
    color: "#c4841d",
    tone: "bg-[#c4841d]",
    character: "Quick, ambitious, irritable, lean.",
    excess: "Anger, burning stomach, jaundice, acute inflammations.",
    treatments: "Cooling, bitter herbs, avoiding spices and sun, sometimes vomiting.",
  },
  {
    id: "black-bile",
    name: "Black bile",
    greek: "Melaina chole",
    temperament: "Melancholic",
    qualities: ["Cold", "Dry"],
    season: "Autumn",
    element: "Earth",
    color: "#3d3428",
    tone: "bg-[#3d3428]",
    character: "Thoughtful, anxious, sleepless, exact.",
    excess: "Sadness, heaviness, stubborn bowel, dark thoughts.",
    treatments: "Warmth, wine in measure, music, company, moist foods — not isolation.",
  },
  {
    id: "phlegm",
    name: "Phlegm",
    greek: "Phlegma",
    temperament: "Phlegmatic",
    qualities: ["Cold", "Wet"],
    season: "Winter",
    element: "Water",
    color: "#5d6e62",
    tone: "bg-[#5d6e62]",
    character: "Calm, slow, steadfast, pale.",
    excess: "Coughs, lethargy, swelling, dull appetite.",
    treatments: "Heat, spices, exercise, drying foods, steam, mustard plasters.",
  },
];
